[project]
name = "datn-project"
version = "0.1.0"
description = "datn-project"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib-inline>=0.1.7",
    "dnse",
    "html2text>=2025.4.15",
    "paho-mqtt>=2.0",
    "python-dotenv>=1.0",
    "requests>=2.31",
    "trading-websocket",
    "vnstock>=3.5.1",
    "s3fs>=2026.3.0",
    "pyarrow>=15.0.0",
    "polars>=1.0.0",
]

[tool.uv.sources]
dnse = { path = "dnse_sdk/dnse", editable = true }
trading-websocket = { path = "dnse_sdk/trading_websocket", editable = true }

[project.optional-dependencies]
vwap = [
    "kafka-python>=2.0.2",
    "clickhouse-connect>=0.7.16",
    "streamlit>=1.32.0",
    "plotly>=5.20.0",
    "pandas>=2.2.0",
    "pyarrow==15.0.0",
    "minio==7.2.7",
    "python-dotenv==1.0.1"
]
